### ISSUE TITLE
Production version fails to negotiate WebSocket upgrade

### ISSUE THREAD

**Issue by embeddedt** [utmgdsc/PollVotingSystem#50]
# Problem

The production version of the poll voting app (https://poll.utm.utoronto.ca/) does not allow clients to upgrade to WebSockets for communication, forcing them to use inefficient HTTP polling instead. This could lead to heavy network traffic when there are many concurrent users.

# Expected behavior

This screenshot is taken by running the production `docker-compose.yaml` setup (including the Nginx proxy) locally and browsing to the root page.
![image](https://user-images.githubusercontent.com/42941056/191833909-a8aeff45-edd9-4cb1-8a48-a5f499419503.png)

# Actual behavior

This screenshot is taken by browsing to https://poll.utm.utoronto.ca/.
![image](https://user-images.githubusercontent.com/42941056/191833955-4ed80ab8-f697-4ec7-aa51-b523c3c94372.png)

**Comment by embeddedt** [comment]
I have gotten the local setup to use HTTPS with a self-signed certificate. Surprisingly, WebSockets still seem to work, so there must be some other difference between this and production. :thinking: 

![image](https://user-images.githubusercontent.com/42941056/191838620-9332fc19-ec29-48e3-805d-27d0eeac84a5.png)

**Comment by shubhbapna** [comment]
I wonder if this related to Shibboleth (It's what we use for UofT SSO)

**Comment by embeddedt** [comment]
It very well could be if Shibboleth proxies HTTP requests. Is there a way of setting up a local instance of that?

**Comment by shubhbapna** [comment]
I haven't tried it but this might work
https://isea.utoronto.ca/services/weblogin/sso-howto-weblogin/

**Comment by shubhbapna** [comment]
Thanks for your help @embeddedt !!!

Just to summarize the solution, we ended up using your configuration for the apache reverse proxy. In addition to that there was a misconfiguration in the reverse proxy which lead to sending the `/socket.io` requests to the wrong place.
