### ISSUE TITLE
Linting and Formatting for the backend

### ISSUE THREAD

**Issue by hiimchrislim** [utmgdsc/PollVotingSystem#62]
**Describe the solution you'd like**

We currently only have linting and formatting set up for the client. Refer to it as an example.
Additionally, a Github action should be made for it as well to run on each PR

**Comment by shubhbapna** [comment]
Additionally update husky to run pre-commit linting for backend as well

**Comment by ggggg** [comment]
Hey can I get assigned to this issue?
