### ISSUE TITLE
Remove use of `any`

### ISSUE THREAD

**Issue by shubhbapna** [utmgdsc/PollVotingSystem#63]
Enforce type checks and remove use of `any`

1.  [getPollStatus](https://github.com/utmgdsc/PollVotingSystem/blob/main/server/src/controllers/pollController.ts#L111)
2. [getResult](https://github.com/utmgdsc/PollVotingSystem/blob/main/server/src/controllers/pollController.ts#L119)
3. [getUser](https://github.com/utmgdsc/PollVotingSystem/blob/main/server/src/controllers/userController.ts#L3)
4. [getStudents](https://github.com/utmgdsc/PollVotingSystem/blob/main/server/src/controllers/pollController.ts#L65)

**Comment by ggggg** [comment]
@shubhbapna can you assign this to me?

**Comment by huonggiangbui** [comment]
> @shubhbapna can you assign this to me?

done!
