### ISSUE TITLE
"9" and "g" are hard to distinguish in poll codes

### ISSUE THREAD

**Issue by embeddedt** [utmgdsc/PollVotingSystem#77]
**Describe the bug**

The font weight/contrast/family choice makes it hard to distinguish between the digit 9 and the letter g, especially on a projector screen.

**To Reproduce**

Create a poll that contains a 9 and g in its code.

**Expected behavior**

The two characters should look different enough to be easily read.

**Screenshots**

The following poll code starts with 9g, however you cannot tell which is which without some very close analysis of the shape.

Apologies for the low-quality picture.

![IMG-0284](https://user-images.githubusercontent.com/42941056/198021843-060856bf-2a26-40a6-849e-e25bd3b8fa35.JPG)

**Comment by shubhbapna** [comment]
lol interesting.

Proposed solution? Use a different font?

**Comment by logonoff** [comment]
could avoid ambiguous characters altogether, 0/o is another likely one

**Comment by ggggg** [comment]
Sticking to numbers only or letters only is the lazy solution, but it would surely work. 
Alternatively we could capitalize all letters which would make most letters easier to differentiate (with the exception of 0/O, but we could avoid 0). 
But I would still to change the font if it were up to me.
We could also make the code much larger.
Or we could implement a multitude of these solutions but thats all I can come up with at the moment.

**Comment by Praj-Pend** [comment]
If the plan is to stick to numbers and letters, perhaps we can colour code numbers and alphabet differently? 

Otherwise, sticking to just numbers or just letters is a good idea, in my opinion.

**Comment by embeddedt** [comment]
I would definitely change the font to something more readable. Someone told me a while ago Helvetica is good for this kind of thing because its glyphs are fairly distinguishable.

**Comment by Praj-Pend** [comment]
I think the 9 and g are still a bit indistinguishable with Helvetica. Perhaps a font like Calibri?

![image](https://user-images.githubusercontent.com/90790532/198754258-91604ed8-9e90-4b45-9b7b-2e20e1ed22b7.png)

Typeface image from freefonts.io

**Comment by ggggg** [comment]
Helvetica is will definitely help but it wont completely solve the issue

**Comment by embeddedt** [comment]
We should do the math; perhaps dropping numbers from codes entirely doesn't reduce the entropy that much.

**Comment by ggggg** [comment]
Any font we choose wont work with 0 and O, or l and 1, or j and i etc...
I think the best way is to go numbers only or letters only.

**Comment by shubhbapna** [comment]
Implementing a custom generator for non-colliding poll code with a character length of 6 is beast on its own. So we ended up using a library called `nanoid`. There is some collision probability involved. Even though its minimal we don't want to take a chance :) (just as @embeddedt pointed out)

So using this [id probability calculator](https://zelark.github.io/nano-id-cc/) I found out the following: 
- using just alphabets we will have a 1% chance of collision in a day if we were to produce 100 poll ids per hour
- using just numbers we will have a 1% chance of collision in an hour if we were to produce 100 poll ids per hour

For reference with current character set (both numbers and alphabets) we will have a 1% chance of collision in 3 days if we were to produce 100 poll ids per hour

So I am comfortable with changing our character set to just alphabets. But for future reference for any changes to poll code please you math to justify your changes. Choosing a character set for poll codes isn't as straightforward ;)

**Comment by shubhbapna** [comment]
This issue if up for grabs. Let me know if you want to submit a PR for it

**Comment by ggggg** [comment]
I'm down, assign me if possible.

**Comment by ggggg** [comment]
Should I also change the font?

**Comment by shubhbapna** [comment]
Uh lets first just change the character set. Make a PR i will ping everyone involved here to check it
