### ISSUE TITLE
Server side type enforcements Github action.

### ISSUE THREAD

**Issue by ggggg** [utmgdsc/PollVotingSystem#81]
**Is your feature request related to a problem? Please describe.**
We should make sure that the typescript build passes without build/type errors before merging PRs (have a look at #70 and #80) 

**Describe the solution you'd like**
Github action that runs every commit/PR running `yarn run build` or `npm build` for the server

**Describe alternatives you've considered**
N/A

**Additional context**
If you approve this issue, please assign it to me if possible.

**Comment by huonggiangbui** [comment]
@shubhbapna Can you check this issue? Is it good to add?

**Comment by shubhbapna** [comment]
Well not really. Once we have the test cases implemented, it will cover this as well
